services:
  - type: web
    name: discord-role-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: DISCORD_TOKEN
        value: YOUR_BOT_TOKEN_HERE
